### ISSUE TITLE
Create the ifl floating window

### ISSUE THREAD

**Issue by SzatmariA** [SzatmariA/CharmFL-dev#16]
We should have sliders in the floating window where you can set the scores for the buggy element or its context

**Comment by SzatmariA** [comment]
@SamuraiSnail will do the mock up wireframes. 

Task:
The floating window should have

- [ ] coloured dots which indicates the level of suspiciousness (score or rank) for each statement
- [ ] Sliders that should have their default values to 1.5 for close context and 1.2 for far context
- [ ] These sliders should be upwards like in a mixing table or in iFL4Eclipse
- [ ] Should have three buttons which show the element or the context

**Comment by SamuraiSnail** [comment]
I have designed a raw wireframe for the floating window. Attached below:
![uiterv](https://user-images.githubusercontent.com/79812254/195092564-169c74dc-28c7-4d96-bd38-e0bc1083429a.PNG)

**Comment by bencireka** [comment]
This may help with the floating window: https://plugins.jetbrains.com/docs/intellij/tool-windows.html
