### ISSUE TITLE
Toolbar menu: buttons are disabled for certain projects

### ISSUE THREAD

**Issue by mpeter50** [SzatmariA/CharmFL-dev#2]
**Describe the bug**
When cloning a repository, it sometimes occurs that after opening it in PyCharm, the buttons in the toolbar menu will be disabled, preventing the user from starting the tests.

**To Reproduce**
1.1 Open PyCharm
1.2 Close any opened projects, if there is any
2. Click on 'Get from VCS'
3. Fill in the URL field with this URL: https://github.com/yt-dlp/yt-dlp
4. When the project has opened and PyCharm has finished preparations (e.g. indexing project files), open the toolbar menu to see that the 'Run' button is disabled.

**Expected behavior**
The 'Run' button in the toolbar should be enabled, so the test can be ran.

**Screenshots**
![kép](https://user-images.githubusercontent.com/83356418/144859729-384b5d84-a98c-4358-a276-71406f8bf059.png)

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox
 - Version: 78.13.0esr

**Additional context**
The issue applies to the included PyCharm plugin of version 1.0.4

**Comment by mpeter50** [comment]
It seems the issue is mitigated by exiting and reopening PyCharm

**Comment by SzatmariA** [comment]
Solved in the new version
