### ISSUE TITLE
Plugin error after all tests are run

### ISSUE THREAD

**Issue by neslielielsen** [SzatmariA/CharmFL-dev#4]
**Describe the bug**
After running all the tests using pytest, a report file is generated, but a plugin error is thrown in certain cases, preventing the fault localization from working.

**To Reproduce**
1. Download source of [httpie 2.6.0](https://github.com/httpie/httpie/releases/tag/2.6.0)
2. Open as PyCharm project
3. Install all required packages in the used venv
4. Click 'CharmFL', then select Run

**Expected behavior**
CharmFL runs without an error, and test metrics are viewable in the IDE.

**Screenshots**

![Screenshot showing error](https://user-images.githubusercontent.com/64501483/144862478-8ed308a5-c7d0-405d-a42a-5caa93c6dbf0.png)

**Desktop (please complete the following information):**
 - OS: Debian 10
 - PyCharm version: 2021.2
 - CharmFL version: v1.0.4

**Additional context**
- Problem occurs with any combination of CharmFL settings.
- There are less test entries in the generated report than in the IDE when running pytest manually.
[report.xlsx](https://github.com/SzatmariA/CharmFL-dev/files/7661378/report.xlsx)

**Comment by SzatmariA** [comment]
This is no longer an issue, since we do not use the openpyxl anymore
