### ISSUE TITLE
Coverage testing CharmFL-dev

### ISSUE THREAD

**Issue by DanielArpadfalvi** [SzatmariA/CharmFL-dev#5]
**Describe the bug**
After we run the built-in coverage test the program describes code coverage as seen below on screenshot:

**To Reproduce**
1. Go to Pycharm, open CharmFL-dev project.
2. Click on main.py, More Run/Debug, run 'main' with coverage to see coverage test results.
3. Browse file structure to see respective coverage results.
4. According to the test mere 45% of main.py is covered, meaning less than half of it is actually used during running, leaving the rest of it as dead code. It is not unforseen in big, legacy projects or just 8-10 year old, never-refactored projects but not expected in small, dense projects like this.

**Expected behavior**
It is expected that the overall coverage of src folder should be well above 70-80%.

![Képernyőkép – 2021-12-08 18-47-41](https://user-images.githubusercontent.com/63950893/145257847-3229f96a-d648-4889-83b8-8bbcc39f29fc.png)

**Desktop (please complete the following information):**
 - It may be irrelevant, however I provide the environment information:
 - OS: [Linux, debian]
 - Browser [mozilla]
 - Version [92]

**Additional information**
- By default I wanted to test a small python project found on github, however due to technical issues during the environment setup I failed to test the above mentioned small project thus decided to test the sourcecode of the plugin itself, which is always interesting. It gives a better understanding about how certain programs work as intended even tough producing average (or even below average) scores on tests such as coverage tests.

**Comment by SzatmariA** [comment]
The tests are still under development, hence the coverage for the backend's code will not result in high scores.
